name: continuous-integration

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: apt-get update
      - run: apt-get build-essential
      - run: apt-get cmake
      - run: ls -a
