name: continuous-integration

on:
  push:
    branches: [main]

jobs:

  continuous-integration:

    runs-on: ubuntu-latest

    steps:

      - run: sudo apt-get update
      - run: sudo apt-get install build-essential
      - run: sudo apt-get install cmake
  
      - uses: actions/checkout@v4
      - run: mkdir build
      - run: cd build
      - run: cmake ..
      - run: make
      
      - run: ./main

